FROM python:3.7-slim

WORKDIR /app

# both files are explicitly required!
COPY requirements.txt ./

RUN apt-get update && \
  apt-get install -y --no-install-recommends gcc python3-dev libssl-dev && \
  pip install -r requirements.txt \
  apt-get remove -y gcc python3-dev libssl-dev && \
  apt-get autoremove -y &&

COPY app ./

CMD ["python", "app.py"]